<cfabort/>
[settings]
mode=production
appname=Mura CMS
appreloadkey=appreload
installed=0
[production]
title=Mura CMS
filedir=
filestore=fileDir
filestoreaccessinfo=
assetpath=
mapdir=mura
webrootmap=muraWRM
datasource=
dbtype=
dbusername=
dbpassword=
context=
stub=
admindomain=
indexfile=index.cfm
adminemail=
mailserverip=
mailserversmtpport=25
mailserverpopport=110
mailserverusername=
mailserverpassword=
mailservertls=false
mailserverssl=false
usedefaultsmtpserver=1
adminssl=0
logevents=0
debuggingenabled=true
port=80
sessionhistory=1
dashboard=true
locale=Server
ping=0
enableMuraTag=true
imageinterpolation=highestQuality
productiondatasource=
productionassetpath=
productionwebroot=
productionfiledir=
clusteriplist=

