<cfabort/>
[settings]
mode=production
appname=Mura CMS
appReloadKey=appreload
installed=0

[production]
title=Mura CMS
filedir=
fileStore=fileDir
fileStoreAccessInfo=
assetpath=/tasks/sites
mapdir=mura
webrootmap=muraWRM
datasource=
dbType=mysql
dbUsername=
dbPassword=
context=
stub=
admindomain=
indexfile=index.cfm
adminemail=name@example.com
mailserverip=mail.example.com
mailserversmtpport=25
mailserverpopport=110
mailserverusername=name@example.com
mailserverpassword=password
mailservertls=false
mailserverssl=false
useDefaultSMTPServer=1
adminssl=0
logEvents=0
debuggingEnabled=true
port=
productionDatasource=
productionAssetPath=
productionWebroot=
productionFiledir=
sessionHistory=1
locale=Server
ping=0
imageInterpolation=highestQuality
clusterIPList=